name: build

on:
  push:
    branches:
      - master

env:
  DOCKER_LOGIN_NAME: ${{ secrets.DOCKER_LOGIN_NAME }}
  DOCKER_LOGIN_PASS: ${{ secrets.DOCKER_LOGIN_PASS }}
  DOCKER_HUB: "registry.cn-hangzhou.aliyuncs.com"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 1.Check out git repository
        uses: actions/checkout@v2

      - name: 2.login aliyun docker hub
        run: echo "${{ env.DOCKER_LOGIN_PASS }}" | docker login "${{ env.DOCKER_HUB }}" -u "${{ env.DOCKER_LOGIN_NAME }}" --password-stdin
      
      - name: 3. build
        run: docker build -t registry.cn-hangzhou.aliyuncs.com/ithreal123/pause:3.5 -f Dockerfile .
      
      - name: 4. push
        run: docker push registry.cn-hangzhou.aliyuncs.com/ithreal123/pause:3.5